### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [Anupya/pic-my-allergy-android#4]
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you (F-Droid members are busy, it can take some time)?

**Comment by Anupya** [comment]
Yes! If you want to add it to F-Droid on my behalf that would be okay. Just make sure to link back to this GitHub and credit me :)
